### ISSUE TITLE
Make darkmode the default

### ISSUE THREAD

**Issue by Sleuth56** [johnholbrook/fll-timer.com#5]
Dark mode doesn't flare cameras, uses less power on certain displays, and it doesn't blind us techies. :)

**Comment by johnholbrook** [comment]
Implemented in the above commit - note that the page stores your theme preference locally to preserve it across page reload. So if the page was in light mode last time you visited (and you haven't cleared your browser cache since then) you'll need to select dark mode manually to update that preference.

But dark mode is now the default when that preference isn't there.
